version: 2.1
references:
  variables:
    maven-cache-path: &maven-cache-path
      - ~/.m2
jobs:
  test:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: ./gradlew spotlessCheck test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test