name: Unit test & build plugin 
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        jdk: [ '17' ]
    name: CI using JDK ${{ matrix.jdk }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }} # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
          distribution: 'microsoft'
      - name: test 
        run: ./gradlew spotlessCheck test
      - name: build plugin
        run: ./gradlew clean zipPlugin 
      - name: run plugin-descriptor test
        run: bash etc/es-plugin-version-test.sh
